//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG.Core.Resources.CalendarResources", typeof(CalendarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить событие.
        /// </summary>
        public static string ActionLabelAddEvent {
            get {
                return ResourceManager.GetString("ActionLabelAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к Календарю.
        /// </summary>
        public static string ActionLabelBackToCalendar {
            get {
                return ResourceManager.GetString("ActionLabelBackToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление событиями.
        /// </summary>
        public static string ActionLabelManageEvent {
            get {
                return ResourceManager.GetString("ActionLabelManageEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие успешно создано..
        /// </summary>
        public static string EventAddSuccessMessage {
            get {
                return ResourceManager.GetString("EventAddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие на весь день.
        /// </summary>
        public static string EventAllDay {
            get {
                return ResourceManager.GetString("EventAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет.
        /// </summary>
        public static string EventColor {
            get {
                return ResourceManager.GetString("EventColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событе {0} будет удалено..
        /// </summary>
        public static string EventDeleteDialogTemplateMessage {
            get {
                return ResourceManager.GetString("EventDeleteDialogTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены ?.
        /// </summary>
        public static string EventDeleteDialogTitle {
            get {
                return ResourceManager.GetString("EventDeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка удаления события. Попробуйте позже..
        /// </summary>
        public static string EventDeleteErrorMessageContent {
            get {
                return ResourceManager.GetString("EventDeleteErrorMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        public static string EventDeleteErrorMessageTitle {
            get {
                return ResourceManager.GetString("EventDeleteErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие удалено..
        /// </summary>
        public static string EventDeleteSuccessMessageContent {
            get {
                return ResourceManager.GetString("EventDeleteSuccessMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно!.
        /// </summary>
        public static string EventDeleteSuccessMessageTitle {
            get {
                return ResourceManager.GetString("EventDeleteSuccessMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие успешно обновлено..
        /// </summary>
        public static string EventEditSuccessMessage {
            get {
                return ResourceManager.GetString("EventEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечная Дата.
        /// </summary>
        public static string EventEndDate {
            get {
                return ResourceManager.GetString("EventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечное Время.
        /// </summary>
        public static string EventEndTime {
            get {
                return ResourceManager.GetString("EventEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        public static string EventFio {
            get {
                return ResourceManager.GetString("EventFio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cover.
        /// </summary>
        public static string EventImageBlobId {
            get {
                return ResourceManager.GetString("EventImageBlobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string EventImageDelete {
            get {
                return ResourceManager.GetString("EventImageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string EventImageDeleteCancelLabel {
            get {
                return ResourceManager.GetString("EventImageDeleteCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string EventImageDeleteConfirmLabel {
            get {
                return ResourceManager.GetString("EventImageDeleteConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены?.
        /// </summary>
        public static string EventImageDeleteTitle {
            get {
                return ResourceManager.GetString("EventImageDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string EventImageDescription {
            get {
                return ResourceManager.GetString("EventImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ярлык.
        /// </summary>
        public static string EventImageLabel {
            get {
                return ResourceManager.GetString("EventImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картинки.
        /// </summary>
        public static string EventImages {
            get {
                return ResourceManager.GetString("EventImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площадка.
        /// </summary>
        public static string EventLocationId {
            get {
                return ResourceManager.GetString("EventLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временная зона расположения будет ассоциирована с событием..
        /// </summary>
        public static string EventLocationIdHint {
            get {
                return ResourceManager.GetString("EventLocationIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string EventProductionId {
            get {
                return ResourceManager.GetString("EventProductionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить событие.
        /// </summary>
        public static string EventsAddHeader {
            get {
                return ResourceManager.GetString("EventsAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите информацию для нового события..
        /// </summary>
        public static string EventsAddLeadInfo {
            get {
                return ResourceManager.GetString("EventsAddLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавиьт событие.
        /// </summary>
        public static string EventsAddSectionLabel {
            get {
                return ResourceManager.GetString("EventsAddSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string EventsCancelLabel {
            get {
                return ResourceManager.GetString("EventsCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        public static string EventsConfirmLabel {
            get {
                return ResourceManager.GetString("EventsConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string EventsDeleteLabel {
            get {
                return ResourceManager.GetString("EventsDeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать событие.
        /// </summary>
        public static string EventsEditHeader {
            get {
                return ResourceManager.GetString("EventsEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string EventsEditLabel {
            get {
                return ResourceManager.GetString("EventsEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить информацию события..
        /// </summary>
        public static string EventsEditLeadInfo {
            get {
                return ResourceManager.GetString("EventsEditLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать событие.
        /// </summary>
        public static string EventsEditSectionLabel {
            get {
                return ResourceManager.GetString("EventsEditSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картинка #%curr% не может быть загружена..
        /// </summary>
        public static string EventsGalleryLoadingErrorMessageTemplate {
            get {
                return ResourceManager.GetString("EventsGalleryLoadingErrorMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружаю картинку #%curr%....
        /// </summary>
        public static string EventsGalleryLoadingMessageTemplate {
            get {
                return ResourceManager.GetString("EventsGalleryLoadingMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список событий.
        /// </summary>
        public static string EventsHeader {
            get {
                return ResourceManager.GetString("EventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление существующими событиями..
        /// </summary>
        public static string EventsLeadInfo {
            get {
                return ResourceManager.GetString("EventsLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        public static string EventsPageLabel {
            get {
                return ResourceManager.GetString("EventsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string EventsSaveLabel {
            get {
                return ResourceManager.GetString("EventsSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление событиями.
        /// </summary>
        public static string EventsSectionLabel {
            get {
                return ResourceManager.GetString("EventsSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальна Дата.
        /// </summary>
        public static string EventStartDate {
            get {
                return ResourceManager.GetString("EventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное Время.
        /// </summary>
        public static string EventStartTime {
            get {
                return ResourceManager.GetString("EventStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип события.
        /// </summary>
        public static string EventTypeId {
            get {
                return ResourceManager.GetString("EventTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        public static string IndexSectionLabel {
            get {
                return ResourceManager.GetString("IndexSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        public static string MenuItemLabel {
            get {
                return ResourceManager.GetString("MenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        public static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружаю....
        /// </summary>
        public static string SendingEventImagesLabel {
            get {
                return ResourceManager.GetString("SendingEventImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предстоящие события.
        /// </summary>
        public static string SidebarCalendarLabel {
            get {
                return ResourceManager.GetString("SidebarCalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить картинку(ки).
        /// </summary>
        public static string UploadEventImagesLabel {
            get {
                return ResourceManager.GetString("UploadEventImagesLabel", resourceCulture);
            }
        }
    }
}
