//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG.Core.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осень.
        /// </summary>
        public static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not Specified.
        /// </summary>
        public static string GenderNotSpecified {
            get {
                return ResourceManager.GetString("GenderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location Type 1.
        /// </summary>
        public static string LocationType1 {
            get {
                return ResourceManager.GetString("LocationType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location Type 2.
        /// </summary>
        public static string LocationType2 {
            get {
                return ResourceManager.GetString("LocationType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location Type 3.
        /// </summary>
        public static string LocationType3 {
            get {
                return ResourceManager.GetString("LocationType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location Type 4.
        /// </summary>
        public static string LocationType4 {
            get {
                return ResourceManager.GetString("LocationType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location Type 5.
        /// </summary>
        public static string LocationType5 {
            get {
                return ResourceManager.GetString("LocationType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin Website.
        /// </summary>
        public static string RealmAdmin {
            get {
                return ResourceManager.GetString("RealmAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BG App.
        /// </summary>
        public static string RealmBG {
            get {
                return ResourceManager.GetString("RealmBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Realm.
        /// </summary>
        public static string RealmLabel {
            get {
                return ResourceManager.GetString("RealmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web Api.
        /// </summary>
        public static string RealmWebApi {
            get {
                return ResourceManager.GetString("RealmWebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrator.
        /// </summary>
        public static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проект.
        /// </summary>
        public static string RolePROJECT {
            get {
                return ResourceManager.GetString("RolePROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УКС.
        /// </summary>
        public static string RoleUKS {
            get {
                return ResourceManager.GetString("RoleUKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УМТОП.
        /// </summary>
        public static string RoleUMTOP {
            get {
                return ResourceManager.GetString("RoleUMTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Весна.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лето.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УКС.
        /// </summary>
        public static string TenderPurpose1 {
            get {
                return ResourceManager.GetString("TenderPurpose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УМТОП.
        /// </summary>
        public static string TenderPurpose2 {
            get {
                return ResourceManager.GetString("TenderPurpose2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупка.
        /// </summary>
        public static string TenderType1 {
            get {
                return ResourceManager.GetString("TenderType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа.
        /// </summary>
        public static string TenderType2 {
            get {
                return ResourceManager.GetString("TenderType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зима.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
    }
}
