//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG.Core.Resources.DashboardResources", typeof(DashboardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статьи.
        /// </summary>
        public static string ArticlesLabel {
            get {
                return ResourceManager.GetString("ArticlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string ContactsLabel {
            get {
                return ResourceManager.GetString("ContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (создать).
        /// </summary>
        public static string CreateNewLabel {
            get {
                return ResourceManager.GetString("CreateNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        public static string EventsLabel {
            get {
                return ResourceManager.GetString("EventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние Статьи.
        /// </summary>
        public static string LatestArticlesLabel {
            get {
                return ResourceManager.GetString("LatestArticlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние Контакты.
        /// </summary>
        public static string LatestContactsLabel {
            get {
                return ResourceManager.GetString("LatestContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние События.
        /// </summary>
        public static string LatestEventsLabel {
            get {
                return ResourceManager.GetString("LatestEventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние Площадки.
        /// </summary>
        public static string LatestLocationsLabel {
            get {
                return ResourceManager.GetString("LatestLocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние Заказы.
        /// </summary>
        public static string LatestOrdersLabel {
            get {
                return ResourceManager.GetString("LatestOrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние задачи.
        /// </summary>
        public static string LatestTasksLabel {
            get {
                return ResourceManager.GetString("LatestTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние Тендеры.
        /// </summary>
        public static string LatestTendersLabel {
            get {
                return ResourceManager.GetString("LatestTendersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площадки.
        /// </summary>
        public static string LocationsLabel {
            get {
                return ResourceManager.GetString("LocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель управления.
        /// </summary>
        public static string MenuItemLabel {
            get {
                return ResourceManager.GetString("MenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы не найдены..
        /// </summary>
        public static string NoItemsMessage {
            get {
                return ResourceManager.GetString("NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы.
        /// </summary>
        public static string OrdersLabel {
            get {
                return ResourceManager.GetString("OrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель управления.
        /// </summary>
        public static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель управления.
        /// </summary>
        public static string SectionLabel {
            get {
                return ResourceManager.GetString("SectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задачи.
        /// </summary>
        public static string TasksLabel {
            get {
                return ResourceManager.GetString("TasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тендеры.
        /// </summary>
        public static string TendersLabel {
            get {
                return ResourceManager.GetString("TendersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (все).
        /// </summary>
        public static string ViewAllLabel {
            get {
                return ResourceManager.GetString("ViewAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За Неделю.
        /// </summary>
        public static string WeeklyRegistrationsLabel {
            get {
                return ResourceManager.GetString("WeeklyRegistrationsLabel", resourceCulture);
            }
        }
    }
}
