//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StateUnitedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateUnitedResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG.Core.Resources.StateUnitedResources", typeof(StateUnitedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ном. зак. клиента.
        /// </summary>
        public static string clientOrderNr {
            get {
                return ResourceManager.GetString("clientOrderNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ном. пос. клиента.
        /// </summary>
        public static string clientParcelNr {
            get {
                return ResourceManager.GetString("clientParcelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузополучатель.
        /// </summary>
        public static string consignee {
            get {
                return ResourceManager.GetString("consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатель.
        /// </summary>
        public static string Consignee2 {
            get {
                return ResourceManager.GetString("Consignee2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель.
        /// </summary>
        public static string Consignor {
            get {
                return ResourceManager.GetString("Consignor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес доставки.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город доставки.
        /// </summary>
        public static string DeliveryCity {
            get {
                return ResourceManager.GetString("DeliveryCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал доставки.
        /// </summary>
        public static string DeliveryInterval {
            get {
                return ResourceManager.GetString("DeliveryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код пункта доставки.
        /// </summary>
        public static string DeliveryPointCode {
            get {
                return ResourceManager.GetString("DeliveryPointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вариант доставки.
        /// </summary>
        public static string DeliveryVariant {
            get {
                return ResourceManager.GetString("DeliveryVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер отправки.
        /// </summary>
        public static string dpdOrderNr {
            get {
                return ResourceManager.GetString("dpdOrderNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ном. пос. dpd.
        /// </summary>
        public static string dpdParcelNr {
            get {
                return ResourceManager.GetString("dpdParcelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посл . событие.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина события.
        /// </summary>
        public static string EventReason {
            get {
                return ResourceManager.GetString("EventReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код инцидента.
        /// </summary>
        public static string incidentCode {
            get {
                return ResourceManager.GetString("incidentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наим. инцидента.
        /// </summary>
        public static string incidentName {
            get {
                return ResourceManager.GetString("incidentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат.
        /// </summary>
        public static string isReturn {
            get {
                return ResourceManager.GetString("isReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат установл..
        /// </summary>
        public static string isReturnSpecified {
            get {
                return ResourceManager.GetString("isReturnSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смещение времени.
        /// </summary>
        public static string MomentLocZone {
            get {
                return ResourceManager.GetString("MomentLocZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние.
        /// </summary>
        public static string newState {
            get {
                return ResourceManager.GetString("newState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип заказа.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес отгрузки.
        /// </summary>
        public static string PickupAddress {
            get {
                return ResourceManager.GetString("PickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город отгрузки.
        /// </summary>
        public static string PickupCity {
            get {
                return ResourceManager.GetString("PickupCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата приема отправки.
        /// </summary>
        public static string pickupDate {
            get {
                return ResourceManager.GetString("pickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на План дата доставки.
        /// </summary>
        public static string planDeliveryDate {
            get {
                return ResourceManager.GetString("planDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на План дата доставки установл..
        /// </summary>
        public static string planDeliveryDateSpecified {
            get {
                return ResourceManager.GetString("planDeliveryDateSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город присв. события.
        /// </summary>
        public static string PointCity {
            get {
                return ResourceManager.GetString("PointCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наим. проблемы.
        /// </summary>
        public static string ProblemName {
            get {
                return ResourceManager.GetString("ProblemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина проблемы.
        /// </summary>
        public static string ReasonName {
            get {
                return ResourceManager.GetString("ReasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина отказа.
        /// </summary>
        public static string RejectionReason {
            get {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город терминала.
        /// </summary>
        public static string terminalCity {
            get {
                return ResourceManager.GetString("terminalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код терминала.
        /// </summary>
        public static string terminalCode {
            get {
                return ResourceManager.GetString("terminalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата транзита.
        /// </summary>
        public static string transitionTime {
            get {
                return ResourceManager.GetString("transitionTime", resourceCulture);
            }
        }
    }
}
