//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimelineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimelineResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG.Core.Resources.TimelineResources", typeof(TimelineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статья Создана.
        /// </summary>
        public static string ArticleCreated {
            get {
                return ResourceManager.GetString("ArticleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статья удалена.
        /// </summary>
        public static string ArticleDeleted {
            get {
                return ResourceManager.GetString("ArticleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория создана.
        /// </summary>
        public static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория статьи удалена.
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый контакт создан..
        /// </summary>
        public static string ContactCreated {
            get {
                return ResourceManager.GetString("ContactCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакт удален..
        /// </summary>
        public static string ContactDeleted {
            get {
                return ResourceManager.GetString("ContactDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактная информация обновлена..
        /// </summary>
        public static string ContactUpdated {
            get {
                return ResourceManager.GetString("ContactUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт создан..
        /// </summary>
        public static string CreatedItsOwnAccount {
            get {
                return ResourceManager.GetString("CreatedItsOwnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано новое событие..
        /// </summary>
        public static string EventCreated {
            get {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие удалено..
        /// </summary>
        public static string EventDeleted {
            get {
                return ResourceManager.GetString("EventDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о событии обновлена..
        /// </summary>
        public static string EventUpdated {
            get {
                return ResourceManager.GetString("EventUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано новое расположение..
        /// </summary>
        public static string LocationCreated {
            get {
                return ResourceManager.GetString("LocationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расположение удалено..
        /// </summary>
        public static string LocationDeleted {
            get {
                return ResourceManager.GetString("LocationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о расположении обновлена..
        /// </summary>
        public static string LocationUpdated {
            get {
                return ResourceManager.GetString("LocationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Еще не активен..
        /// </summary>
        public static string NotActivityMessage {
            get {
                return ResourceManager.GetString("NotActivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создан новый тендер..
        /// </summary>
        public static string TenderCreated {
            get {
                return ResourceManager.GetString("TenderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тендер удален..
        /// </summary>
        public static string TenderDeleted {
            get {
                return ResourceManager.GetString("TenderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тендер обновлен..
        /// </summary>
        public static string TenderUpdated {
            get {
                return ResourceManager.GetString("TenderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие сведения обновлены..
        /// </summary>
        public static string UpdatedItsOwnGeneralSettings {
            get {
                return ResourceManager.GetString("UpdatedItsOwnGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация профиля обновлена..
        /// </summary>
        public static string UpdatedItsOwnProfileInformation {
            get {
                return ResourceManager.GetString("UpdatedItsOwnProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус обновлен..
        /// </summary>
        public static string UpdatedItsOwnStatusMessage {
            get {
                return ResourceManager.GetString("UpdatedItsOwnStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя активность.
        /// </summary>
        public static string UserTimelineLabel {
            get {
                return ResourceManager.GetString("UserTimelineLabel", resourceCulture);
            }
        }
    }
}
