//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG.Core.Resources.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пару слов о себе..
        /// </summary>
        public static string AboutYourselfLabel {
            get {
                return ResourceManager.GetString("AboutYourselfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт.
        /// </summary>
        public static string AccountLabel {
            get {
                return ResourceManager.GetString("AccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт.
        /// </summary>
        public static string AccountPageLabel {
            get {
                return ResourceManager.GetString("AccountPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт.
        /// </summary>
        public static string AccountSectionLabel {
            get {
                return ResourceManager.GetString("AccountSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор.
        /// </summary>
        public static string AccountTab1Label {
            get {
                return ResourceManager.GetString("AccountTab1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о профиле.
        /// </summary>
        public static string AccountTab2Label {
            get {
                return ResourceManager.GetString("AccountTab2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие установки.
        /// </summary>
        public static string AccountTab3Label {
            get {
                return ResourceManager.GetString("AccountTab3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавть пользователя.
        /// </summary>
        public static string ActionLabelAdd {
            get {
                return ResourceManager.GetString("ActionLabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавть пользователя.
        /// </summary>
        public static string AddHeader {
            get {
                return ResourceManager.GetString("AddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите информацию для нового пользователя.
        /// </summary>
        public static string AddLeadInfo {
            get {
                return ResourceManager.GetString("AddLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddSectionLabel {
            get {
                return ResourceManager.GetString("AddSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоблокировка Экрана..
        /// </summary>
        public static string AutoLockScreenInMinutes {
            get {
                return ResourceManager.GetString("AutoLockScreenInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биография.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль не верный..
        /// </summary>
        public static string ChangePasswordCurrentInvalidMessage {
            get {
                return ResourceManager.GetString("ChangePasswordCurrentInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите необходимую информация для изменения пароля..
        /// </summary>
        public static string ChangePasswordInfo {
            get {
                return ResourceManager.GetString("ChangePasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменит пароль.
        /// </summary>
        public static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePasswordPageLabel {
            get {
                return ResourceManager.GetString("ChangePasswordPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите Пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат дат, времени и цифр..
        /// </summary>
        public static string CurrentCultureHint {
            get {
                return ResourceManager.GetString("CurrentCultureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string CurrentCultureId {
            get {
                return ResourceManager.GetString("CurrentCultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported language translations..
        /// </summary>
        public static string CurrentUICultureHint {
            get {
                return ResourceManager.GetString("CurrentUICultureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string CurrentUICultureId {
            get {
                return ResourceManager.GetString("CurrentUICultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать пользователя..
        /// </summary>
        public static string EditHeader {
            get {
                return ResourceManager.GetString("EditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновите идентификационную информацию пользователя..
        /// </summary>
        public static string EditLeadInfo {
            get {
                return ResourceManager.GetString("EditLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать пользователя..
        /// </summary>
        public static string EditSectionLabel {
            get {
                return ResourceManager.GetString("EditSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получается принять ваш e-mail. Попробуйте еще..
        /// </summary>
        public static string EmailConfirmationCallbackErrorMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationCallbackErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получается  отправить сообщение проверки e-mail. Попробуйте еще..
        /// </summary>
        public static string EmailConfirmationMessageError {
            get {
                return ResourceManager.GetString("EmailConfirmationMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо!.
        /// </summary>
        public static string EmailConfirmationMessageLabel {
            get {
                return ResourceManager.GetString("EmailConfirmationMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка Email.
        /// </summary>
        public static string EmailConfirmationMessageSentPageLabel {
            get {
                return ResourceManager.GetString("EmailConfirmationMessageSentPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Проверка.
        /// </summary>
        public static string EmailConfirmationMessageSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение о проверке был отправлен на ваш e-mail..
        /// </summary>
        public static string EmailConfirmationMessageSuccess {
            get {
                return ResourceManager.GetString("EmailConfirmationMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string EmailOrUsername {
            get {
                return ResourceManager.GetString("EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Региональные установки.
        /// </summary>
        public static string GlobalizationLabel {
            get {
                return ResourceManager.GetString("GlobalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка.
        /// </summary>
        public static string ImageBlobId {
            get {
                return ResourceManager.GetString("ImageBlobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string InstagramLink {
            get {
                return ResourceManager.GetString("InstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные имя пользователя или пароль..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль неверный..
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями..
        /// </summary>
        public static string LeadInfo {
            get {
                return ResourceManager.GetString("LeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked In.
        /// </summary>
        public static string LinkedInLink {
            get {
                return ResourceManager.GetString("LinkedInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать экран.
        /// </summary>
        public static string LockScreenLabel {
            get {
                return ResourceManager.GetString("LockScreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокировать автоматически:.
        /// </summary>
        public static string LockScreenSettingsAutoLabel {
            get {
                return ResourceManager.GetString("LockScreenSettingsAutoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключено.
        /// </summary>
        public static string LockScreenSettingsAutoValudeDisabled {
            get {
                return ResourceManager.GetString("LockScreenSettingsAutoValudeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После {interval} минут..
        /// </summary>
        public static string LockScreenSettingsAutoValueTemplate {
            get {
                return ResourceManager.GetString("LockScreenSettingsAutoValueTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать экран.
        /// </summary>
        public static string LockScreenSettingsLabel {
            get {
                return ResourceManager.GetString("LockScreenSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть аккаунт ?.
        /// </summary>
        public static string LoginCallOutLabel {
            get {
                return ResourceManager.GetString("LoginCallOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вспомнил?.
        /// </summary>
        public static string LoginCallOutLabel2 {
            get {
                return ResourceManager.GetString("LoginCallOutLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to.
        /// </summary>
        public static string LoginCalloutLabel3 {
            get {
                return ResourceManager.GetString("LoginCalloutLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginPageLabel {
            get {
                return ResourceManager.GetString("LoginPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOffLabel {
            get {
                return ResourceManager.GetString("LogOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MenuItemLabel {
            get {
                return ResourceManager.GetString("MenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя..
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите новый пароль.
        /// </summary>
        public static string NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о статусе успешно обновлена..
        /// </summary>
        public static string OverviewDataSuccessMessage {
            get {
                return ResourceManager.GetString("OverviewDataSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменен!.
        /// </summary>
        public static string PasswordChangeSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональная Информация.
        /// </summary>
        public static string PersonalInformationLabel {
            get {
                return ResourceManager.GetString("PersonalInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать аккаунт..
        /// </summary>
        public static string ProfileCompletionAccountLabel {
            get {
                return ResourceManager.GetString("ProfileCompletionAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполненность профиля.
        /// </summary>
        public static string ProfileCompletionLabel {
            get {
                return ResourceManager.GetString("ProfileCompletionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнофить биографию..
        /// </summary>
        public static string ProfileCompletionUpdateBiographyLabel {
            get {
                return ResourceManager.GetString("ProfileCompletionUpdateBiographyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить картинку..
        /// </summary>
        public static string ProfileCompletionUpdatePictureLabel {
            get {
                return ResourceManager.GetString("ProfileCompletionUpdatePictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнофите инф-ю о Ваших соц. сетях..
        /// </summary>
        public static string ProfileCompletionUpdateSocialMediaLabel {
            get {
                return ResourceManager.GetString("ProfileCompletionUpdateSocialMediaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте ваш e-mail..
        /// </summary>
        public static string ProfileCompletionVerifyEmailLabel {
            get {
                return ResourceManager.GetString("ProfileCompletionVerifyEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль успешно обновлен..
        /// </summary>
        public static string ProfileDataUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("ProfileDataUpdatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка пользователя.
        /// </summary>
        public static string ProfilePictureLabel {
            get {
                return ResourceManager.GetString("ProfilePictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm.
        /// </summary>
        public static string Realm {
            get {
                return ResourceManager.GetString("Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать.
        /// </summary>
        public static string RegisterButtonLabel {
            get {
                return ResourceManager.GetString("RegisterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще не зарегистрированы?.
        /// </summary>
        public static string RegisterCallOutLabel {
            get {
                return ResourceManager.GetString("RegisterCallOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterPageLabel {
            get {
                return ResourceManager.GetString("RegisterPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить!.
        /// </summary>
        public static string ResetPasswordButtonLabel {
            get {
                return ResourceManager.GetString("ResetPasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reset token. Please request a new one..
        /// </summary>
        public static string ResetPasswordGeneralErrorMessage {
            get {
                return ResourceManager.GetString("ResetPasswordGeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваш e-mail для получения инструкции по сбросу пароля..
        /// </summary>
        public static string ResetPasswordInformation {
            get {
                return ResourceManager.GetString("ResetPasswordInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить Пароль.
        /// </summary>
        public static string ResetPasswordMessageSubject {
            get {
                return ResourceManager.GetString("ResetPasswordMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс Пароля.
        /// </summary>
        public static string ResetPasswordPageLabel {
            get {
                return ResourceManager.GetString("ResetPasswordPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно!.
        /// </summary>
        public static string ResetPasswordSuccessLabel {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция для сброса пароля отправлена..
        /// </summary>
        public static string ResetPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string SectionLabel {
            get {
                return ResourceManager.GetString("SectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безопасность.
        /// </summary>
        public static string SecurityLabel {
            get {
                return ResourceManager.GetString("SecurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установки аккаунта успешно обновлены..
        /// </summary>
        public static string SettingsDataUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("SettingsDataUpdatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Profile Links.
        /// </summary>
        public static string SocialMediaProfilesLabel {
            get {
                return ResourceManager.GetString("SocialMediaProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string StatusMessage {
            get {
                return ResourceManager.GetString("StatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to опубликовать.
        /// </summary>
        public static string StatusMessageUpdateLabel {
            get {
                return ResourceManager.GetString("StatusMessageUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о статусе.
        /// </summary>
        public static string StatusSettingsHint {
            get {
                return ResourceManager.GetString("StatusSettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string StatusSettingsLabel {
            get {
                return ResourceManager.GetString("StatusSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условиями.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я согласен с  {0}..
        /// </summary>
        public static string TermsOfUseSentenceTemplate {
            get {
                return ResourceManager.GetString("TermsOfUseSentenceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временная Зона.
        /// </summary>
        public static string TimeZoneId {
            get {
                return ResourceManager.GetString("TimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша временная зона.
        /// </summary>
        public static string TimeZoneIdHint {
            get {
                return ResourceManager.GetString("TimeZoneIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать.
        /// </summary>
        public static string UnlockLabel {
            get {
                return ResourceManager.GetString("UnlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не {0}?.
        /// </summary>
        public static string UnlockScreenQuestionTemplate {
            get {
                return ResourceManager.GetString("UnlockScreenQuestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка Загрузки!.
        /// </summary>
        public static string UploadErrorMessageTitle {
            get {
                return ResourceManager.GetString("UploadErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить картинку.
        /// </summary>
        public static string UploadImageLabel {
            get {
                return ResourceManager.GetString("UploadImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаю....
        /// </summary>
        public static string UploadSendingLabel {
            get {
                return ResourceManager.GetString("UploadSendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно обновлен..
        /// </summary>
        public static string UserEditSuccessMessage {
            get {
                return ResourceManager.GetString("UserEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин..
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только буквы и цифры, начинается с буквы..
        /// </summary>
        public static string UserNameHint {
            get {
                return ResourceManager.GetString("UserNameHint", resourceCulture);
            }
        }
    }
}
