//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.DPDServices.BGDPDServiceEventTracking {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class WSFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class auth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long clientNumberField;
        
        private string clientKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long clientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
                this.RaisePropertyChanged("clientNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
                this.RaisePropertyChanged("clientKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class requestConfirm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private long docIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
                this.RaisePropertyChanged("docId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", ConfigurationName="BGDPDServiceEventTracking.DPDEventTracking")]
    public interface DPDEventTracking {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/confirmRequest", ReplyAction="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/confirmResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceEventTracking.WSFault), Action="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/confirm/Fault/WSFault" +
            "", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceEventTracking.confirmResponse confirm(BG.DPDServices.BGDPDServiceEventTracking.confirmRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/getEventsRequest", ReplyAction="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/getEventsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceEventTracking.WSFault), Action="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/getEvents/Fault/WSFau" +
            "lt", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceEventTracking.getEventsResponse getEvents(BG.DPDServices.BGDPDServiceEventTracking.getEventsRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/getTrakingOrderLinkRe" +
            "quest", ReplyAction="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/getTrakingOrderLinkRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceEventTracking.WSFault), Action="http://dpd.ru/ws/event-tracking/2016-02-15/DPDEventTracking/getTrakingOrderLink/F" +
            "ault/WSFault", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkResponse getTrakingOrderLink(BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirm", WrapperNamespace="http://dpd.ru/ws/event-tracking/2016-02-15", IsWrapped=true)]
    public partial class confirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceEventTracking.requestConfirm request;
        
        public confirmRequest() {
        }
        
        public confirmRequest(BG.DPDServices.BGDPDServiceEventTracking.requestConfirm request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmResponse", WrapperNamespace="http://dpd.ru/ws/event-tracking/2016-02-15", IsWrapped=true)]
    public partial class confirmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public confirmResponse() {
        }
        
        public confirmResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class eventTrackingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private System.DateTime dateFromField;
        
        private bool dateFromFieldSpecified;
        
        private System.DateTime dateToField;
        
        private bool dateToFieldSpecified;
        
        private int maxRowCountField;
        
        private bool maxRowCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
                this.RaisePropertyChanged("dateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateFromSpecified {
            get {
                return this.dateFromFieldSpecified;
            }
            set {
                this.dateFromFieldSpecified = value;
                this.RaisePropertyChanged("dateFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
                this.RaisePropertyChanged("dateTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateToSpecified {
            get {
                return this.dateToFieldSpecified;
            }
            set {
                this.dateToFieldSpecified = value;
                this.RaisePropertyChanged("dateToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int maxRowCount {
            get {
                return this.maxRowCountField;
            }
            set {
                this.maxRowCountField = value;
                this.RaisePropertyChanged("maxRowCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxRowCountSpecified {
            get {
                return this.maxRowCountFieldSpecified;
            }
            set {
                this.maxRowCountFieldSpecified = value;
                this.RaisePropertyChanged("maxRowCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class eventTackingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long docIdField;
        
        private System.DateTime docDateField;
        
        private long clientNumberField;
        
        private bool resultCompleteField;
        
        private eventType[] eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
                this.RaisePropertyChanged("docId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
                this.RaisePropertyChanged("docDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long clientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
                this.RaisePropertyChanged("clientNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool resultComplete {
            get {
                return this.resultCompleteField;
            }
            set {
                this.resultCompleteField = value;
                this.RaisePropertyChanged("resultComplete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public eventType[] @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("event");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class eventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientOrderNrField;
        
        private string clientCodeInternalField;
        
        private string clientParcelNrField;
        
        private string dpdOrderNrField;
        
        private string dpdParcelNrField;
        
        private string eventNumberField;
        
        private string eventCodeField;
        
        private string eventNameField;
        
        private string reasonCodeField;
        
        private string reasonNameField;
        
        private string eventDateField;
        
        private parameterType[] parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientOrderNr {
            get {
                return this.clientOrderNrField;
            }
            set {
                this.clientOrderNrField = value;
                this.RaisePropertyChanged("clientOrderNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientCodeInternal {
            get {
                return this.clientCodeInternalField;
            }
            set {
                this.clientCodeInternalField = value;
                this.RaisePropertyChanged("clientCodeInternal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clientParcelNr {
            get {
                return this.clientParcelNrField;
            }
            set {
                this.clientParcelNrField = value;
                this.RaisePropertyChanged("clientParcelNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dpdOrderNr {
            get {
                return this.dpdOrderNrField;
            }
            set {
                this.dpdOrderNrField = value;
                this.RaisePropertyChanged("dpdOrderNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dpdParcelNr {
            get {
                return this.dpdParcelNrField;
            }
            set {
                this.dpdParcelNrField = value;
                this.RaisePropertyChanged("dpdParcelNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string eventNumber {
            get {
                return this.eventNumberField;
            }
            set {
                this.eventNumberField = value;
                this.RaisePropertyChanged("eventNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eventCode {
            get {
                return this.eventCodeField;
            }
            set {
                this.eventCodeField = value;
                this.RaisePropertyChanged("eventCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string eventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("eventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string reasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("reasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string reasonName {
            get {
                return this.reasonNameField;
            }
            set {
                this.reasonNameField = value;
                this.RaisePropertyChanged("reasonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
                this.RaisePropertyChanged("eventDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public parameterType[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class parameterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paramNameField;
        
        private string valueStringField;
        
        private decimal valueDecimalField;
        
        private bool valueDecimalFieldSpecified;
        
        private System.DateTime valueDateTimeField;
        
        private bool valueDateTimeFieldSpecified;
        
        private eventTrackingUnitLoad[] valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paramName {
            get {
                return this.paramNameField;
            }
            set {
                this.paramNameField = value;
                this.RaisePropertyChanged("paramName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string valueString {
            get {
                return this.valueStringField;
            }
            set {
                this.valueStringField = value;
                this.RaisePropertyChanged("valueString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal valueDecimal {
            get {
                return this.valueDecimalField;
            }
            set {
                this.valueDecimalField = value;
                this.RaisePropertyChanged("valueDecimal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueDecimalSpecified {
            get {
                return this.valueDecimalFieldSpecified;
            }
            set {
                this.valueDecimalFieldSpecified = value;
                this.RaisePropertyChanged("valueDecimalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime valueDateTime {
            get {
                return this.valueDateTimeField;
            }
            set {
                this.valueDateTimeField = value;
                this.RaisePropertyChanged("valueDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueDateTimeSpecified {
            get {
                return this.valueDateTimeFieldSpecified;
            }
            set {
                this.valueDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("valueDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public eventTrackingUnitLoad[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class eventTrackingUnitLoad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string articleField;
        
        private string descriptField;
        
        private string declared_valueField;
        
        private string parcel_numField;
        
        private string npp_amountField;
        
        private int vat_percentField;
        
        private bool vat_percentFieldSpecified;
        
        private bool without_vatField;
        
        private bool without_vatFieldSpecified;
        
        private int countField;
        
        private string state_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string article {
            get {
                return this.articleField;
            }
            set {
                this.articleField = value;
                this.RaisePropertyChanged("article");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descript {
            get {
                return this.descriptField;
            }
            set {
                this.descriptField = value;
                this.RaisePropertyChanged("descript");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string declared_value {
            get {
                return this.declared_valueField;
            }
            set {
                this.declared_valueField = value;
                this.RaisePropertyChanged("declared_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string parcel_num {
            get {
                return this.parcel_numField;
            }
            set {
                this.parcel_numField = value;
                this.RaisePropertyChanged("parcel_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string npp_amount {
            get {
                return this.npp_amountField;
            }
            set {
                this.npp_amountField = value;
                this.RaisePropertyChanged("npp_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int vat_percent {
            get {
                return this.vat_percentField;
            }
            set {
                this.vat_percentField = value;
                this.RaisePropertyChanged("vat_percent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vat_percentSpecified {
            get {
                return this.vat_percentFieldSpecified;
            }
            set {
                this.vat_percentFieldSpecified = value;
                this.RaisePropertyChanged("vat_percentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool without_vat {
            get {
                return this.without_vatField;
            }
            set {
                this.without_vatField = value;
                this.RaisePropertyChanged("without_vat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool without_vatSpecified {
            get {
                return this.without_vatFieldSpecified;
            }
            set {
                this.without_vatFieldSpecified = value;
                this.RaisePropertyChanged("without_vatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string state_name {
            get {
                return this.state_nameField;
            }
            set {
                this.state_nameField = value;
                this.RaisePropertyChanged("state_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEvents", WrapperNamespace="http://dpd.ru/ws/event-tracking/2016-02-15", IsWrapped=true)]
    public partial class getEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceEventTracking.eventTrackingRequest request;
        
        public getEventsRequest() {
        }
        
        public getEventsRequest(BG.DPDServices.BGDPDServiceEventTracking.eventTrackingRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsResponse", WrapperNamespace="http://dpd.ru/ws/event-tracking/2016-02-15", IsWrapped=true)]
    public partial class getEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceEventTracking.eventTackingResponse @return;
        
        public getEventsResponse() {
        }
        
        public getEventsResponse(BG.DPDServices.BGDPDServiceEventTracking.eventTackingResponse @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class extTrackingLinkRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private order orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public order order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberDPDField;
        
        private string orderNumberInternalField;
        
        private string orderNumberInternalAdditionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNumberDPD {
            get {
                return this.orderNumberDPDField;
            }
            set {
                this.orderNumberDPDField = value;
                this.RaisePropertyChanged("orderNumberDPD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string orderNumberInternal {
            get {
                return this.orderNumberInternalField;
            }
            set {
                this.orderNumberInternalField = value;
                this.RaisePropertyChanged("orderNumberInternal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string orderNumberInternalAdditional {
            get {
                return this.orderNumberInternalAdditionalField;
            }
            set {
                this.orderNumberInternalAdditionalField = value;
                this.RaisePropertyChanged("orderNumberInternalAdditional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15")]
    public partial class extTrackingLinkResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string linkField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTrakingOrderLink", WrapperNamespace="http://dpd.ru/ws/event-tracking/2016-02-15", IsWrapped=true)]
    public partial class getTrakingOrderLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceEventTracking.extTrackingLinkRequest trackingOrder;
        
        public getTrakingOrderLinkRequest() {
        }
        
        public getTrakingOrderLinkRequest(BG.DPDServices.BGDPDServiceEventTracking.extTrackingLinkRequest trackingOrder) {
            this.trackingOrder = trackingOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTrakingOrderLinkResponse", WrapperNamespace="http://dpd.ru/ws/event-tracking/2016-02-15", IsWrapped=true)]
    public partial class getTrakingOrderLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/event-tracking/2016-02-15", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceEventTracking.extTrackingLinkResponse @return;
        
        public getTrakingOrderLinkResponse() {
        }
        
        public getTrakingOrderLinkResponse(BG.DPDServices.BGDPDServiceEventTracking.extTrackingLinkResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DPDEventTrackingChannel : BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DPDEventTrackingClient : System.ServiceModel.ClientBase<BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking>, BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking {
        
        public DPDEventTrackingClient() {
        }
        
        public DPDEventTrackingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DPDEventTrackingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DPDEventTrackingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DPDEventTrackingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceEventTracking.confirmResponse BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking.confirm(BG.DPDServices.BGDPDServiceEventTracking.confirmRequest request) {
            return base.Channel.confirm(request);
        }
        
        public string confirm(BG.DPDServices.BGDPDServiceEventTracking.requestConfirm request) {
            BG.DPDServices.BGDPDServiceEventTracking.confirmRequest inValue = new BG.DPDServices.BGDPDServiceEventTracking.confirmRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceEventTracking.confirmResponse retVal = ((BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking)(this)).confirm(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceEventTracking.getEventsResponse BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking.getEvents(BG.DPDServices.BGDPDServiceEventTracking.getEventsRequest request) {
            return base.Channel.getEvents(request);
        }
        
        public BG.DPDServices.BGDPDServiceEventTracking.eventTackingResponse getEvents(BG.DPDServices.BGDPDServiceEventTracking.eventTrackingRequest request) {
            BG.DPDServices.BGDPDServiceEventTracking.getEventsRequest inValue = new BG.DPDServices.BGDPDServiceEventTracking.getEventsRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceEventTracking.getEventsResponse retVal = ((BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking)(this)).getEvents(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkResponse BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking.getTrakingOrderLink(BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkRequest request) {
            return base.Channel.getTrakingOrderLink(request);
        }
        
        public BG.DPDServices.BGDPDServiceEventTracking.extTrackingLinkResponse getTrakingOrderLink(BG.DPDServices.BGDPDServiceEventTracking.extTrackingLinkRequest trackingOrder) {
            BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkRequest inValue = new BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkRequest();
            inValue.trackingOrder = trackingOrder;
            BG.DPDServices.BGDPDServiceEventTracking.getTrakingOrderLinkResponse retVal = ((BG.DPDServices.BGDPDServiceEventTracking.DPDEventTracking)(this)).getTrakingOrderLink(inValue);
            return retVal.@return;
        }
    }
}
