//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.DPDServices.BGDPDServiceTracing {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class WSFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class stateParcel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientOrderNrField;
        
        private string clientParcelNrField;
        
        private string dpdOrderNrField;
        
        private string dpdParcelNrField;
        
        private System.DateTime pickupDateField;
        
        private string dpdOrderReNrField;
        
        private string dpdParcelReNrField;
        
        private bool isReturnField;
        
        private bool isReturnFieldSpecified;
        
        private System.DateTime planDeliveryDateField;
        
        private bool planDeliveryDateFieldSpecified;
        
        private string newStateField;
        
        private System.DateTime transitionTimeField;
        
        private string terminalCodeField;
        
        private string terminalCityField;
        
        private string incidentCodeField;
        
        private string incidentNameField;
        
        private string consigneeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientOrderNr {
            get {
                return this.clientOrderNrField;
            }
            set {
                this.clientOrderNrField = value;
                this.RaisePropertyChanged("clientOrderNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientParcelNr {
            get {
                return this.clientParcelNrField;
            }
            set {
                this.clientParcelNrField = value;
                this.RaisePropertyChanged("clientParcelNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dpdOrderNr {
            get {
                return this.dpdOrderNrField;
            }
            set {
                this.dpdOrderNrField = value;
                this.RaisePropertyChanged("dpdOrderNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dpdParcelNr {
            get {
                return this.dpdParcelNrField;
            }
            set {
                this.dpdParcelNrField = value;
                this.RaisePropertyChanged("dpdParcelNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime pickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
                this.RaisePropertyChanged("pickupDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dpdOrderReNr {
            get {
                return this.dpdOrderReNrField;
            }
            set {
                this.dpdOrderReNrField = value;
                this.RaisePropertyChanged("dpdOrderReNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dpdParcelReNr {
            get {
                return this.dpdParcelReNrField;
            }
            set {
                this.dpdParcelReNrField = value;
                this.RaisePropertyChanged("dpdParcelReNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool isReturn {
            get {
                return this.isReturnField;
            }
            set {
                this.isReturnField = value;
                this.RaisePropertyChanged("isReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isReturnSpecified {
            get {
                return this.isReturnFieldSpecified;
            }
            set {
                this.isReturnFieldSpecified = value;
                this.RaisePropertyChanged("isReturnSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=8)]
        public System.DateTime planDeliveryDate {
            get {
                return this.planDeliveryDateField;
            }
            set {
                this.planDeliveryDateField = value;
                this.RaisePropertyChanged("planDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool planDeliveryDateSpecified {
            get {
                return this.planDeliveryDateFieldSpecified;
            }
            set {
                this.planDeliveryDateFieldSpecified = value;
                this.RaisePropertyChanged("planDeliveryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string newState {
            get {
                return this.newStateField;
            }
            set {
                this.newStateField = value;
                this.RaisePropertyChanged("newState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime transitionTime {
            get {
                return this.transitionTimeField;
            }
            set {
                this.transitionTimeField = value;
                this.RaisePropertyChanged("transitionTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string terminalCode {
            get {
                return this.terminalCodeField;
            }
            set {
                this.terminalCodeField = value;
                this.RaisePropertyChanged("terminalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string terminalCity {
            get {
                return this.terminalCityField;
            }
            set {
                this.terminalCityField = value;
                this.RaisePropertyChanged("terminalCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string incidentCode {
            get {
                return this.incidentCodeField;
            }
            set {
                this.incidentCodeField = value;
                this.RaisePropertyChanged("incidentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string incidentName {
            get {
                return this.incidentNameField;
            }
            set {
                this.incidentNameField = value;
                this.RaisePropertyChanged("incidentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string consignee {
            get {
                return this.consigneeField;
            }
            set {
                this.consigneeField = value;
                this.RaisePropertyChanged("consignee");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class stateParcels : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long docIdField;
        
        private System.DateTime docDateField;
        
        private long clientNumberField;
        
        private bool resultCompleteField;
        
        private stateParcel[] statesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
                this.RaisePropertyChanged("docId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
                this.RaisePropertyChanged("docDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long clientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
                this.RaisePropertyChanged("clientNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool resultComplete {
            get {
                return this.resultCompleteField;
            }
            set {
                this.resultCompleteField = value;
                this.RaisePropertyChanged("resultComplete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("states", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public stateParcel[] states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
                this.RaisePropertyChanged("states");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class auth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long clientNumberField;
        
        private string clientKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long clientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
                this.RaisePropertyChanged("clientNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
                this.RaisePropertyChanged("clientKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", ConfigurationName="BGDPDServiceTracing.ParcelTracing")]
    public interface ParcelTracing {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientRequest", ReplyAction="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceTracing.WSFault), Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClient/Fault/WSFault" +
            "", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceTracing.getStatesByClientResponse getStatesByClient(BG.DPDServices.BGDPDServiceTracing.getStatesByClientRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientOrderRequest", ReplyAction="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceTracing.WSFault), Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientOrder/Fault/WS" +
            "Fault", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderResponse getStatesByClientOrder(BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientParcelRequest", ReplyAction="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientParcelResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceTracing.WSFault), Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByClientParcel/Fault/W" +
            "SFault", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelResponse getStatesByClientParcel(BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByDPDOrderRequest", ReplyAction="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByDPDOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceTracing.WSFault), Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/getStatesByDPDOrder/Fault/WSFau" +
            "lt", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderResponse getStatesByDPDOrder(BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/confirmRequest", ReplyAction="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/confirmResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BG.DPDServices.BGDPDServiceTracing.WSFault), Action="http://dpd.ru/ws/tracing/2011-11-18/ParcelTracing/confirm/Fault/WSFault", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BG.DPDServices.BGDPDServiceTracing.confirmResponse confirm(BG.DPDServices.BGDPDServiceTracing.confirmRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByClient", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.requestClient request;
        
        public getStatesByClientRequest() {
        }
        
        public getStatesByClientRequest(BG.DPDServices.BGDPDServiceTracing.requestClient request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByClientResponse", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.stateParcels @return;
        
        public getStatesByClientResponse() {
        }
        
        public getStatesByClientResponse(BG.DPDServices.BGDPDServiceTracing.stateParcels @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestClientOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private string clientOrderNrField;
        
        private System.DateTime pickupDateField;
        
        private bool pickupDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientOrderNr {
            get {
                return this.clientOrderNrField;
            }
            set {
                this.clientOrderNrField = value;
                this.RaisePropertyChanged("clientOrderNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime pickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
                this.RaisePropertyChanged("pickupDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pickupDateSpecified {
            get {
                return this.pickupDateFieldSpecified;
            }
            set {
                this.pickupDateFieldSpecified = value;
                this.RaisePropertyChanged("pickupDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByClientOrder", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByClientOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.requestClientOrder request;
        
        public getStatesByClientOrderRequest() {
        }
        
        public getStatesByClientOrderRequest(BG.DPDServices.BGDPDServiceTracing.requestClientOrder request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByClientOrderResponse", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByClientOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.stateParcels @return;
        
        public getStatesByClientOrderResponse() {
        }
        
        public getStatesByClientOrderResponse(BG.DPDServices.BGDPDServiceTracing.stateParcels @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestClientParcel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private string clientParcelNrField;
        
        private System.DateTime pickupDateField;
        
        private bool pickupDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientParcelNr {
            get {
                return this.clientParcelNrField;
            }
            set {
                this.clientParcelNrField = value;
                this.RaisePropertyChanged("clientParcelNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime pickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
                this.RaisePropertyChanged("pickupDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pickupDateSpecified {
            get {
                return this.pickupDateFieldSpecified;
            }
            set {
                this.pickupDateFieldSpecified = value;
                this.RaisePropertyChanged("pickupDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByClientParcel", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByClientParcelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.requestClientParcel request;
        
        public getStatesByClientParcelRequest() {
        }
        
        public getStatesByClientParcelRequest(BG.DPDServices.BGDPDServiceTracing.requestClientParcel request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByClientParcelResponse", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByClientParcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.stateParcels @return;
        
        public getStatesByClientParcelResponse() {
        }
        
        public getStatesByClientParcelResponse(BG.DPDServices.BGDPDServiceTracing.stateParcels @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestDpdOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private string dpdOrderNrField;
        
        private int pickupYearField;
        
        private bool pickupYearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dpdOrderNr {
            get {
                return this.dpdOrderNrField;
            }
            set {
                this.dpdOrderNrField = value;
                this.RaisePropertyChanged("dpdOrderNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pickupYear {
            get {
                return this.pickupYearField;
            }
            set {
                this.pickupYearField = value;
                this.RaisePropertyChanged("pickupYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pickupYearSpecified {
            get {
                return this.pickupYearFieldSpecified;
            }
            set {
                this.pickupYearFieldSpecified = value;
                this.RaisePropertyChanged("pickupYearSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByDPDOrder", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByDPDOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.requestDpdOrder request;
        
        public getStatesByDPDOrderRequest() {
        }
        
        public getStatesByDPDOrderRequest(BG.DPDServices.BGDPDServiceTracing.requestDpdOrder request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatesByDPDOrderResponse", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class getStatesByDPDOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.stateParcels @return;
        
        public getStatesByDPDOrderResponse() {
        }
        
        public getStatesByDPDOrderResponse(BG.DPDServices.BGDPDServiceTracing.stateParcels @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestConfirm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auth authField;
        
        private long docIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
                this.RaisePropertyChanged("docId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirm", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class confirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BG.DPDServices.BGDPDServiceTracing.requestConfirm request;
        
        public confirmRequest() {
        }
        
        public confirmRequest(BG.DPDServices.BGDPDServiceTracing.requestConfirm request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmResponse", WrapperNamespace="http://dpd.ru/ws/tracing/2011-11-18", IsWrapped=true)]
    public partial class confirmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public confirmResponse() {
        }
        
        public confirmResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParcelTracingChannel : BG.DPDServices.BGDPDServiceTracing.ParcelTracing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParcelTracingClient : System.ServiceModel.ClientBase<BG.DPDServices.BGDPDServiceTracing.ParcelTracing>, BG.DPDServices.BGDPDServiceTracing.ParcelTracing {
        
        public ParcelTracingClient() {
        }
        
        public ParcelTracingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParcelTracingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParcelTracingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParcelTracingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceTracing.getStatesByClientResponse BG.DPDServices.BGDPDServiceTracing.ParcelTracing.getStatesByClient(BG.DPDServices.BGDPDServiceTracing.getStatesByClientRequest request) {
            return base.Channel.getStatesByClient(request);
        }
        
        public BG.DPDServices.BGDPDServiceTracing.stateParcels getStatesByClient(BG.DPDServices.BGDPDServiceTracing.requestClient request) {
            BG.DPDServices.BGDPDServiceTracing.getStatesByClientRequest inValue = new BG.DPDServices.BGDPDServiceTracing.getStatesByClientRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceTracing.getStatesByClientResponse retVal = ((BG.DPDServices.BGDPDServiceTracing.ParcelTracing)(this)).getStatesByClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderResponse BG.DPDServices.BGDPDServiceTracing.ParcelTracing.getStatesByClientOrder(BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderRequest request) {
            return base.Channel.getStatesByClientOrder(request);
        }
        
        public BG.DPDServices.BGDPDServiceTracing.stateParcels getStatesByClientOrder(BG.DPDServices.BGDPDServiceTracing.requestClientOrder request) {
            BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderRequest inValue = new BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceTracing.getStatesByClientOrderResponse retVal = ((BG.DPDServices.BGDPDServiceTracing.ParcelTracing)(this)).getStatesByClientOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelResponse BG.DPDServices.BGDPDServiceTracing.ParcelTracing.getStatesByClientParcel(BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelRequest request) {
            return base.Channel.getStatesByClientParcel(request);
        }
        
        public BG.DPDServices.BGDPDServiceTracing.stateParcels getStatesByClientParcel(BG.DPDServices.BGDPDServiceTracing.requestClientParcel request) {
            BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelRequest inValue = new BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceTracing.getStatesByClientParcelResponse retVal = ((BG.DPDServices.BGDPDServiceTracing.ParcelTracing)(this)).getStatesByClientParcel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderResponse BG.DPDServices.BGDPDServiceTracing.ParcelTracing.getStatesByDPDOrder(BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderRequest request) {
            return base.Channel.getStatesByDPDOrder(request);
        }
        
        public BG.DPDServices.BGDPDServiceTracing.stateParcels getStatesByDPDOrder(BG.DPDServices.BGDPDServiceTracing.requestDpdOrder request) {
            BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderRequest inValue = new BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceTracing.getStatesByDPDOrderResponse retVal = ((BG.DPDServices.BGDPDServiceTracing.ParcelTracing)(this)).getStatesByDPDOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG.DPDServices.BGDPDServiceTracing.confirmResponse BG.DPDServices.BGDPDServiceTracing.ParcelTracing.confirm(BG.DPDServices.BGDPDServiceTracing.confirmRequest request) {
            return base.Channel.confirm(request);
        }
        
        public string confirm(BG.DPDServices.BGDPDServiceTracing.requestConfirm request) {
            BG.DPDServices.BGDPDServiceTracing.confirmRequest inValue = new BG.DPDServices.BGDPDServiceTracing.confirmRequest();
            inValue.request = request;
            BG.DPDServices.BGDPDServiceTracing.confirmResponse retVal = ((BG.DPDServices.BGDPDServiceTracing.ParcelTracing)(this)).confirm(inValue);
            return retVal.@return;
        }
    }
}
